spring.application.name=demo-backend
# 端口号
server.port=8080

# 数据库连接配置
spring.datasource.url=jdbc:mysql://localhost:3306/demo_project?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 数据源连接池配置（HikariCP）
spring.datasource.hikari.maximum-pool-size=10

# 配置mybatis 主要配置xml扫描的路径
mybatis.type-aliases-package=com.example.demobackend.entity
mybatis.mapper-locations=classpath*:mapper/*.xml
mybatis.configuration.jdbc-type-for-null=null
mybatis.configuration.map-underscore-to-camel-case=true


